hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
	hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
	hl.exec_cmd("hyprpaper & waybar")
	hl.exec_cmd("discord --opaque-bg --enable-features=UseOzonePlatform --ozone-platform=wayland")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("systemctl --user start import-environment DISPLAY WAYLAND_DISPLAY")
	hl.exec_cmd("systemctl --user start pipewire pipewire-pulse")
    hl.exec_cmd("qbittorrent")
    hl.exec_cmd("kdeconnectd")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
end)
